import type { Metadata } from 'next';
import { Red_Hat_Display } from 'next/font/google';
import './globals.css';

const redHatDisplay = Red_Hat_Display({
  subsets: ['latin'],
  variable: '--font-redhat', // untuk CSS variable
  display: 'swap', // recommended
});

export const metadata: Metadata = {
  title: "Handi Irawan's portofolio",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark' data-scroll-behavior='smooth'>
      <body className={redHatDisplay.variable}>{children}</body>
    </html>
  );
}
