import type { Metadata } from 'next';
import { Red_Hat_Display } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';

const redHatDisplay = Red_Hat_Display({
  subsets: ['latin'],
  variable: '--font-redhat',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Handi Irawan's portofolio",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={cn('dark', redHatDisplay.className)}
      data-scroll-behavior='smooth'
    >
      <body>
        <main id='main-content'>{children}</main>
      </body>
    </html>
  );
}
